[package]
name = "fencyc"
version = "0.5.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
qbe = { path = "../qbe-rs" }
# qbe = { git = "https://github.com/Freemorger/qbe-rs.git" }
# voxvm = { git = "https://github.com/Freemorger/voxvm.git" } # good old times
