[package]
name = "fencyc"
version = "0.4.3"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
qbe = "2.5.1"
# voxvm = { git = "https://github.com/Freemorger/voxvm.git" }
